name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: lab7a
        id: lab7a
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7a
          command: python3 ./CheckLab7.py -f -v lab7a
          expected-output: "OK"
          timeout: 10
      
      - name: lab7b
        id: lab7b
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7b
          command: python3 ./CheckLab7.py -f -v lab7b
          expected-output: "OK"
          timeout: 10
      
      - name: lab7c
        id: lab7c
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7c
          command: python3 ./CheckLab7.py -f -v lab7c
          expected-output: "OK"
          timeout: 10
      
      - name: lab7d
        id: lab7d
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7d
          command: python3 ./CheckLab7.py -f -v lab7d
          expected-output: "OK"
          timeout: 10
      
      - name: lab7e
        id: lab7e
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7e
          command: python3 ./CheckLab7.py -f -v lab7e
          expected-output: "OK"
          timeout: 10
      
      - name: lab7f
        id: lab7f
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7f
          command: python3 ./CheckLab7.py -f -v lab7f
          expected-output: "OK"
          timeout: 10
      
      - name: lab7g
        id: lab7g
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7g
          command: python3 ./CheckLab7.py -f -v lab7g
          expected-output: "OK"
          timeout: 10
      
      - name: lab7h
        id: lab7h
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7h
          command: python3 ./CheckLab7.py -f -v lab7h
          expected-output: "OK"
          timeout: 10
      
      - name: lab7i
        id: lab7i
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: lab7i
          command: python3 ./CheckLab7.py -f -v lab7i
          expected-output: "OK"
          timeout: 10
      
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          LAB7A_RESULTS: ${{ steps.lab7a.outputs.result }}
          LAB7B_RESULTS: ${{ steps.lab7b.outputs.result }}
          LAB7C_RESULTS: ${{ steps.lab7c.outputs.result }}
          LAB7D_RESULTS: ${{ steps.lab7d.outputs.result }}
          LAB7E_RESULTS: ${{ steps.lab7e.outputs.result }}
          LAB7F_RESULTS: ${{ steps.lab7f.outputs.result }}
          LAB7G_RESULTS: ${{ steps.lab7g.outputs.result }}
          LAB7H_RESULTS: ${{ steps.lab7h.outputs.result }}
          LAB7I_RESULTS: ${{ steps.lab7i.outputs.result }}
        with:
          runners: lab7a,lab7b,lab7c,lab7d,lab7e,lab7f,lab7g,lab7h,lab7i
